### ISSUE TITLE
transfer ownership of Synthizer Rust packages

### ISSUE THREAD

**Issue by ahicks92** [ndarilek/synthizer-rs#1]
We've discussed giving me access before, and I intend to have idiomatic, reasonably documented 0.9 bindings in a few weeks at the latest.  How do you fee about just transferring ownership of the crates?

Figured I'd get ahead of this now in case it takes time or something, but we can wait until I have something to show that's more than my word if you want.

**Comment by ndarilek** [comment]
I can get to this in the next day or two, but to confirm, you'd prefer a 
full transfer of ownership vs. just being added as a collaborator? I'm 
happy to do either--I know that you have a lot to do, and I want to do 
what I can to support continued maintenance. I don't want to step on any 
toes, but do want to see these bindings maintained once the API is stable.

**Comment by ahicks92** [comment]
Yeah, I'd like to go full ownership.  I intend this to be as official as the library itself.  I already wrote over half of it yesterday, and the whole reference-counting handles thing I put in 0.9 is in part for Rust etc.  Se [this repository](https://github.com/synthizer/synthizer-rs) for the current state, though the readme should really say more.

I might have the rest of it today.  "weeks" turned out to be the pessimistic timeline for a change.

**Comment by ahicks92** [comment]
No, I didn't intend to close it. Sorry.

**Comment by ndarilek** [comment]
OK. Do you want ownership of this code, or are you rewriting it from 
scratch and just want crate ownership? I thought I already added you to 
that a while back.

**Comment by ahicks92** [comment]
I did it from scratch.  This issue is for crates.io, not a repo transfer.  I wanted to get rid of the derive dependencies and things, plus everything is like `Arc` now and so on.  I can try to enumerate the differences if you want.

I don't have any access to the crate, as far as I can see.  I know we discussed it but I don't think it ever happened.

**Comment by ndarilek** [comment]
OK, hmm, I feel like I tried to do this a while back. Have you logged 
into crates.io? Typing your GitHub username and clicking Save on the 
owners screen gives no indication that it did anything. Do you have any 
pending invitations either from a while back, or from now when I tried a 
few times?

**Comment by ahicks92** [comment]
I just got one now.  This seems to be good.  I'll reopen if I fail to upload for some reason.

Thanks.

**Comment by ahicks92** [comment]
I lied. I also need synthizer-sys.

**Comment by ndarilek** [comment]
Should've been added to that too. Please let me know if not.

**Comment by ahicks92** [comment]
Got it.  Will leave this open for now, let's wait until my first successful publish to call it good.

**Comment by ahicks92** [comment]
Ok, Synthizer bindings are complete and on crates.io.  Closing this out.

As a sidenote they work on all platforms according to my CI.  I know that's of interest to you.
